language: java
cache:
  directories:
  - $HOME/.m2
mysql:
  database: db_oauth
  username: root
  password :
  encoding: utf8
jdk:
  - oraclejdk8
install:
  - mvn clean install -Dmaven.test.skip=true -s ./.m2/settings.xml
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_oauth;'
script:
  - mvn test -s ./.m2/settings.xml
after_success:
  - mvn test jacoco:report coveralls:report -s ./.m2/settings.xml
notifications:
  email:
    - heyuxian.me@gmail.com