server:
  port: 8043
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: mcloud-oauth-server
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost/db_oauth
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
    show-sql: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

management:
  context-path: /monitoring
  security:
    enabled: false
eureka:
  instance:
    hostname: mcloud-oauth-server
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    metadata-map:
      management:
        context-path: ${server.context-path}${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnU/x82VEqJn3pjx8LJi87UItHmDcgAgByl7TpmzIqXlsnEM6lt8DsznwX/3bqi9GxhXyW0IPRrC4g4lIZRqUlFC6W8x/azzmfbmIpyUv9kVNpuk52BlzULvHKxjbqjQTQFqxFeu0nFQK4B/gDu9Zj6xbb19Yc9b8jkguakNNjzDE+sGwja0WekGuBnqcS8pwTxkRG8lsUSaWsVjLXQVS5MCdZgGjv/abMqIwAPFXdrlbAMKp+epSuMGrGO7j8pLGBjOmoGSHzqZ90DtTIzu4HIgykTo0UqdT/RNoHPCMnhcf0FzqtMU7XQlIIJJ2x2TiUws1uYY0IdPZusKy2K1ntwIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource
      filter-order: 3

swagger:
  title: MCloud-OAuth2 Server
  description: http://javaroad.me